# Generated by Django 4.0.2 on 2022-03-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
