# Generated by Django 4.0.2 on 2022-03-03 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_date_added_alter_book_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
